language: node_js
node_js:
  - stable

cache: 
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'
  - 'yarn test'

before_deploy:
  - yarn build
  - ls

deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_S3_BUCKET_NAME
  skip_cleanup: true
  # Path to a directory containing your built site.
  local_dir: build

notifications:
  email:
    recipients:
      - 8735132@gmail.com
      - 8735132@naver.com
      - jhokta7@daum.net
    on_success: change # default: change
    on_failure: always # default: always

