language: node_js
node_js:
  - stable

install:
  - yarn

scripts:
  - yarn test
  - yarn build
  - ls

deploy:
  on:
    branch: develop
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_S3_BUCKET_NAME
  skip_cleanup: true
  # Path to a directory containing your built site.
  local_dir: build

notifications:
  email:
    recipients:
      - 8735132@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

