language: node_js
node_js:
  - "iojs"
  - "8.10.0"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true


deploy:
  providers: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  email: 8735132@gmail.com
  on:
    branch: master